Use messages from language labels in JS config (fixes #76)
terminal42/contao-fineuploader pull request #81
Opened 2021-03-23 17:00 UTC by gmpf

`ConfigGenerator#generateJavaScriptConfig()` should provide the message labels from the language files. That config then has to be passed in `handler.js`.

2021-03-23 17:01 UTC, gmpf commented
By the way, `ConfigGenerator#generateLabels()` provides even more labels than just messages. All are set in `ConfigGenerator#generateFromWidgetAttributes()`, but not used anywhere.

2021-03-23 17:09 UTC, fritzmg approved these changes

2021-03-24 18:30 UTC, qzminski requested changes

2021-03-24 18:30 UTC, qzminski commented on src/ConfigGenerator.php
> +            'messages' => $labels['messages'],
I think we can safely use `$config->getLabels()['messages']` here instead of having another variable.

2021-03-25 11:07 UTC, gmpf commented on src/ConfigGenerator.php
> +            'messages' => $labels['messages'],
Sure can. :) Just to clarify why I used a variable there: If you would have wanted to add more stuff from `ConfigGenerator#generateLabels()` later on, the next diff would have been clearer that way (kind of the same reasoning for the already-existing code using a trailing comma after the final element). But that was purely speculative on my part. Changed.

2021-03-25 11:30 UTC, qzminski approved these changes

2021-06-21 14:20 UTC, merged

2021-06-21 14:21 UTC, aschempp commented
Thank you @gmpf