Extended field size e.g. for language insert tags
terminal42/contao-fineuploader pull request #89
Opened 2022-07-22 11:44 UTC by zonky2

Extended field size e.g. for language insert tags

2022-07-22 12:46 UTC, fritzmg requested changes
You also need to change the `maxlength` in `eval`.

2022-07-22 13:06 UTC, fritzmg approved these changes

2022-08-09 08:07 UTC, aschempp approved these changes

2022-08-09 08:07 UTC, merged

2022-08-09 08:07 UTC, aschempp commented
Thank you @zonky2