Add compatibility with Haste 5
terminal42/contao-fineuploader pull request #92
Opened 2022-10-26 13:30 UTC by qzminski

2022-10-26 15:29 UTC, fritzmg commented on contao/templates/fineuploader_backend.html5
> +        <?php $template = new \Contao\BackendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
Why this change? Isn't `$this->insert` preferable?

2022-10-27 07:03 UTC, Toflar requested changes

2022-10-27 07:03 UTC, Toflar commented on src/ChunkUploader.php
> +        $this->requestStack->getSession()->get($sessionKey, $chunks);
This will fail in Contao 4.9 because Symfony 4.4 does not provide this method. Either use the current request or raise the minimum version to Contao 4.13 which would be fine for me.

2022-10-27 07:03 UTC, Toflar commented on contao/templates/fineuploader_frontend.html5
> +        <?php $template = new \Contao\FrontendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
Why this change?

2022-10-27 07:03 UTC, Toflar commented on contao/templates/fineuploader_backend.html5
> +        <?php $template = new \Contao\BackendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
Why this change?

2022-10-27 07:03 UTC, Toflar commented on src/WidgetHelper.php
> +            $figure = $this->studio
This too, will fail in Contao 4.9.

2022-10-27 07:09 UTC, qzminski commented on contao/templates/fineuploader_backend.html5
> +        <?php $template = new \Contao\BackendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
I had to disable the Contao debug template comments (`<!-- TEMPLATE START: …`) as they were causing issues in the Fineuploader template in the dev mode.

2022-10-27 07:09 UTC, qzminski commented on contao/templates/fineuploader_frontend.html5
> +        <?php $template = new \Contao\FrontendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
I had to disable the Contao debug template comments (`<!-- TEMPLATE START: …`) as they were causing issues in the Fineuploader template in the dev mode.

2022-10-27 07:13 UTC, Toflar commented
I'd prefer to find another solution and get to the bottom of why an HTML comment is an issue?

2022-10-27 07:24 UTC, qzminski commented
Regarding the `$this->insert()` change, it was necessary, because otherwise in dev mode Contao generated the debug template comments:

<img width="1225" alt="CleanShot 2022-10-27 at 09 19 05" src="https://user-images.githubusercontent.com/193483/198217713-2e42c0b7-bdb6-4010-8524-774a79ac7627.png">

Which resulted in FineUploader being unable to use the template to render the stuff:

<img width="597" alt="CleanShot 2022-10-27 at 09 23 50" src="https://user-images.githubusercontent.com/193483/198217814-937e3832-b2e8-48ae-9dff-14d5e21c0fc9.png">

I think it's better to use the new way, rather than fiddle around with `Config::set('debugMode', …)`.

2022-10-27 07:25 UTC, qzminski commented on contao/templates/fineuploader_backend.html5
> +        <?php $template = new \Contao\BackendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
See my reply in comments of this PR.

2022-10-27 07:25 UTC, qzminski commented on contao/templates/fineuploader_frontend.html5
> +        <?php $template = new \Contao\FrontendTemplate('fineuploader_uploader', $this->arrConfiguration); $template->setDebug(false); echo $template->parse(); ?>
See my reply in comments of this PR.

2022-10-27 08:49 UTC, Toflar commented
We should try to remove HTML comments in our own `hander.js` before initializing FineUploader. Then we can go back to `$this->insert()`. Disabling the debug mode is only a partial solution because if I add a comment myself in the template, things would fail again.

2022-10-27 08:59 UTC, qzminski commented
I have added the JS code to remove the HTML comments, so we can use `$this->insert()` again even in Contao debug mode.

2022-10-27 09:03 UTC, Toflar approved these changes
LGTM, let's fan this out as a new minor! Thanks <3

2022-10-27 09:04 UTC, merged